#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-levi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-levi
  template:
    metadata:
      labels:
        app: prod-stedi-levi
    spec:
      containers:
        - name: prod-stedi-levi
          image: gcr.io/cubs-consulting/stedi  #Replacing this later with new artifact
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: levi-twilio-dev
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-levi"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-levi-nodeport
spec:
  selector:
    app: prod-stedi-levi
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-prod-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-levi-public
    networking.gke.io/managed-certificates: prod-stedi-levi-certificate
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-levi-nodeport
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-levi-certificate # this needs to match line 68
spec:
  domains:
    - levi.cit262.com #This is a DNS record that has not been created yet - We need to create that first
    
